---

- name: Modprobe
  command: modprobe br_netfilter

- name: Apertura de puerto para que el servicio masquerade 
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled

- name: Reiniciar firewall
  command: firewall-cmd --reload

- name: Autorizar a Kubernetes a gestionar el trafico
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: yes

- name: Aplicar cambios en /etc/sysctl.d/k8s.conf
  command: sysctl --system

- name: Repositorio de docker
  command: "/usr/bin/dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  become: yes

- name: Instalando docker-ce
  dnf:
    name: "docker-ce-19.03.14-3.el8"
    state: present
  become: yes

- name: Instalando containerd.io
  dnf:
    name: "containerd.io"
    state: present
  become: yes

- name: Arranque de docker
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes

- name: Configura el repositorio de kubernetes
  copy:
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  become: yes

- name: Kubelet
  dnf:
    name: "kubelet"
    state: present
    disable_excludes: "kubernetes"
  become: yes

- name: Kubeadm
  dnf:
    name: "kubeadm"
    state: present
    disable_excludes: "kubernetes"
  become: yes

- name: kubectl
  dnf:
    name: "kubectl"
    state: present
    disable_excludes: "kubernetes"
  become: yes

- name: Iniciar kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes