---

- name: Apertura puerto 6443/tcp
  firewalld:
    port: 6443/tcp
    permanent: true
    state: enabled

- name: Apertura puerto 2379-2380/tcp 
  firewalld:
    port: 2379-2380/tcp
    permanent: true
    state: enabled

- name: Apertura puerto 10250/tcp
  firewalld:
    port: 10250/tcp
    permanent: true
    state: enabled

- name: Apertura puerto 10251/tcp
  firewalld:
    port: 10251/tcp
    permanent: true
    state: enabled

- name: Apertura puerto 10252/tcp
  firewalld:
    port: 10252/tcp
    permanent: true
    state: enabled

- name: Apertura puerto 10255/tcp
  firewalld:
    port: 10255/tcp
    permanent: true
    state: enabled

- name: Reiniciar firewall
  command: firewall-cmd --reload

- name: Configurar kubeadm (descarga de imágenes)
  command: kubeadm config images pull

- name: Apertura desde Worker01 al Master
  firewalld:
    rich_rule: rule family=ipv4 source address={{ ip_worker01 }}/32 accept
    permanent: true
    state: enabled

- name: Apertura desde Worker02 al Master
  firewalld:
    rich_rule: rule family=ipv4 source address={{ ip_worker02 }}/32 accept
    permanent: true
    state: enabled

- name: Reiniciar firewall
  command: firewall-cmd --reload

- name: Permitir acceso localde los contenedores a localhost
  firewalld:
    rich_rule: rule family=ipv4 source address={{ docker_network }}/16 accept
    zone: public
    permanent: true
    state: enabled

- name: Reiniciar firewall
  command: firewall-cmd --reload

- name: Plugin CNI de Kubernetes
  command: kubeadm init --pod-network-cidr {{ pods_network }}/16 --apiserver-advertise-address {{ ip_master }}
  register: kubeadm_init
  become: true

- name: Permitir acceso rooter al cluster (crear directorio /root/.kube)
  command: mkdir -p /root/.kube
  become: true

- name: Permitir acceso rooter al cluster (copiar fichero /etc/kubernetes/admin.conf a /root/.kube/config)
  command: cp /etc/kubernetes/admin.conf /root/.kube/config
  become: true

- name: Permitir acceso rooter al cluster (cambiar el propietario del fichero /root/.kube/config)
  file: 
    path: /root/.kube/config
    owner: root
    group: root
  become: true